import "./globals.css"
import "normalize.css/normalize.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="w-[1300px] max-[1440px]:w-[100%] mx-auto min-h-screen grid grid-cols-1 items-start">
        {children}
      </body>
    </html>
  )
}
